[package]
name = "serde_gelf"
version = "0.1.0"
authors = ["Cédric Dumay <cedric.dumay@gmail.com>"]
edition = "2018"

[features]
ldp = []

[dependencies]
serde = "1.0"
serde-value = "0.5"
serde_json = "1.0"